### ISSUE TITLE
Parity with maki1 for iD

### ISSUE THREAD

**Issue by bhousel** [mapbox/maki#270]
This is more FYI, and not necessarily a to-do.  I chatted with @natslaughter today, here is a generated list of icons that iD is using from maki1 that are not in maki2:
- [x] ~~camera~~  -> attraction
- [x] ~~chemist~~ -> pharmacy
- [x] city #307
- [x] emergency-telephone #306 
- [x] ~~industrial #308~~ -> industry
- [x] logging #309 
- [x] marker-stroked #310 
- [x] mobile-phone #311 
- [x] park-alt1 #315
- [x] scooter #263
- [x] slaughterhouse #312
- [x] ~~toilets~~  -> toilet
- [x] town #313 
- [x] village #314 

Also I did notice some icons have changed semantically and we would need to change how we use them:
- [x] barrier (we were using prison for all kinds of gate-like things, barriers, fences, etc) #316
- [x] fence (similar to barrier although specifically for fence-like barriers) #324
- [x] entrance-alt1 (we were using it for entrances to buildings / parking garages, not just escalators) #317

Also if we're doing requests, we could use
- [x] defibrillator (will cover AED / defibrillator) #104 #318
- [x] recycling #152
- [x] landuse ("generic" land-use) #319
- [x] natural/landcover (like "landuse" but only natural things) #328
- [x] horse-riding #304

Thanks!!  Love the new maki2 icons! 👍 

cc @kepta
cc @nickidlugash

**Comment by aparlato** [comment]
I made a couple of minor changes to clarify the needs from the above list. Specifically I changed prison to gate and made the note reference that we were using prison for this previously.

**Comment by nickidlugash** [comment]
@aparlato @natslaughter should we consider [this request for a horse-riding icon](https://github.com/mapbox/maki/issues/304) as part of this push?

**Comment by aparlato** [comment]
^ just started this (horse riding icon) and will work on it tomorrow. I'm in favor of adding it to the mix.

![image](https://cloud.githubusercontent.com/assets/15698320/21209896/0858c968-c22c-11e6-88fa-b81a4c76ca25.png)

**Comment by natslaughter** [comment]
@bhousel 
Here is where the icons stand as of today. @samanpwbb, @nickidlugash, @aparlato and I met yesterday and came up with a plan to finish this up and incorporate them into the Maki catalogue next Monday or Tuesday. 

| Icon       | 11 x 11    | 15 x 15  |
| :------------- |:---|:----|
| Logging      | ![logging-11](https://cloud.githubusercontent.com/assets/15698320/21236319/6ddf32bc-c2af-11e6-8bdc-33f3778db661.png) | ![loggin-15](https://cloud.githubusercontent.com/assets/15698320/21236346/858bcef2-c2af-11e6-9371-43248fb4bbaf.png)|
| Barrier | ![barrier-11](https://cloud.githubusercontent.com/assets/15698320/21236372/9f67af1c-c2af-11e6-928a-8fe13f956a1f.png)|![barrier-15](https://cloud.githubusercontent.com/assets/15698320/21236384/a74071c4-c2af-11e6-9edf-0fce9993f72e.png)|
|Park-alt1 | ![park-alt1-11](https://cloud.githubusercontent.com/assets/15698320/21236425/d09a8b18-c2af-11e6-83a4-af1d9bd4dc0e.png) | ![park-alt1-15](https://cloud.githubusercontent.com/assets/15698320/21236434/e084fa40-c2af-11e6-9b68-9ba27e37098b.png) |
| Entrance-alt1 | ![entrance-alt1-11](https://cloud.githubusercontent.com/assets/15698320/21236468/05a466c6-c2b0-11e6-83be-867fa907c5cf.png) | ![entrance-alt1-15](https://cloud.githubusercontent.com/assets/15698320/21236482/0e03430a-c2b0-11e6-9f48-73fea31f51af.png) |
| Landuse | ![landuse-11](https://cloud.githubusercontent.com/assets/15698320/21236519/3080b3fe-c2b0-11e6-8abb-32c39bb6fa8a.png) | ![landuse-15](https://cloud.githubusercontent.com/assets/15698320/21236542/473315ba-c2b0-11e6-978e-c57f74d42a22.png) |
| Mobile-phone | ![mobile-phone-11](https://cloud.githubusercontent.com/assets/15698320/21236570/6ec026f4-c2b0-11e6-92c9-88a6ae377414.png) | ![mobile-phone-15](https://cloud.githubusercontent.com/assets/15698320/21236577/7cab997e-c2b0-11e6-99af-93256825e571.png) |
| Emergency-phone | ![emergency-phone-11](https://cloud.githubusercontent.com/assets/15698320/21236595/935bcaea-c2b0-11e6-8d62-3ade2572aa56.png) | ![emergency-phone-15](https://cloud.githubusercontent.com/assets/15698320/21236623/a328ab78-c2b0-11e6-8014-696ed7310bed.png) |
| City | ![city-11](https://cloud.githubusercontent.com/assets/15698320/21236793/46b01ac4-c2b1-11e6-8b74-0193618bfadf.png) | ![city-15](https://cloud.githubusercontent.com/assets/15698320/21236710/006f32ac-c2b1-11e6-8eb4-9d060ef9ebe7.png) |
| Town | ![town-11](https://cloud.githubusercontent.com/assets/15698320/21236736/1b10f078-c2b1-11e6-8ee5-0360e3b22d52.png) | ![town-15](https://cloud.githubusercontent.com/assets/15698320/21236755/280dbfd6-c2b1-11e6-8620-5136812b20f9.png) |
| Village | ![village-11](https://cloud.githubusercontent.com/assets/15698320/21236814/58f48012-c2b1-11e6-878b-6f01a1deba52.png) | ![village-15](https://cloud.githubusercontent.com/assets/15698320/21236833/6666c2a0-c2b1-11e6-89b6-7f1db69c3342.png) |
| Defibrillator (bolt)      | ![defibrillator-bolt_11](https://cloud.githubusercontent.com/assets/16616543/21238640/c7d43bc4-c2d1-11e6-9f85-91acd1b1fc29.png) | ![defibrillator-bolt_15](https://cloud.githubusercontent.com/assets/16616543/21238654/d6b704be-c2d1-11e6-8fb6-6e614e6d4c4f.png) |  
| Defibrillator (ekg)| ![defibrillator-ekg_11](https://cloud.githubusercontent.com/assets/16616543/21238664/e1630868-c2d1-11e6-9fd2-7b1ca1b19bbd.png) | ![defibrillator-ekg_15](https://cloud.githubusercontent.com/assets/16616543/21238678/ed5ab01c-c2d1-11e6-9115-9d7b95793e78.png) |
| Slaughterhouse     | ![slaughterhouse_11](https://cloud.githubusercontent.com/assets/16616543/21238569/86b9836a-c2d1-11e6-9641-3e120b7bf93d.png) | ![slaughterhouse_15](https://cloud.githubusercontent.com/assets/16616543/21238582/910a623a-c2d1-11e6-8649-0c1ddac8fac1.png) |
| Horse-riding | ![horse-riding-11](https://cloud.githubusercontent.com/assets/15698320/21238921/b2d9d4c6-c2b9-11e6-923b-4093a1a9dffb.png)|![horse-riding-15](https://cloud.githubusercontent.com/assets/15698320/21238925/b973e4fc-c2b9-11e6-8736-2549af4716d8.png) |

**Comment by natslaughter** [comment]
@bhousel 
Thanks for letting us know about the 'natural/landcover' icon need. 
I'm going to suggest we hold off on it for this round of icons, since we are finished with the icons and are merging them into Maki today. 
Let's treat this as an individual icon request #328.

**Comment by aparlato** [comment]
Closing #270

Released all these icons :+1:

**Comment by bhousel** [comment]
Thank you for all your work on this!

**Comment by bhousel** [comment]
cc @ajithranka who is working on the maki migration for iD.
